-- MySQL Script generated by MySQL Workbench
-- Tue Feb 19 16:27:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trepubdotnet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trepubdotnet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trepubdotnet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `trepubdotnet` ;

-- -----------------------------------------------------
-- Table `trepubdotnet`.`appconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`appconfig` (
  `AppConfigId` VARCHAR(128) NOT NULL,
  `AppConfigValue` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`AppConfigId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `trepubdotnet`.`idmap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`idmap` (
  `IDKey` VARCHAR(128) NOT NULL,
  `IDValue` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `trepubdotnet`.`party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`party` (
  `PartyId` BIGINT UNSIGNED NOT NULL,
  `Name` VARCHAR(64) NULL,
  `LastName` VARCHAR(64) NULL,
  `Type` CHAR(2) NOT NULL,
  `Status` CHAR(2) NOT NULL,
  `ExternalId` VARCHAR(255) NULL,
  `Phone` VARCHAR(255) NULL,
  `Address` VARCHAR(255) NULL,
  `BankAccId` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`PartyId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `trepubdotnet`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`profile` (
  `ProfileId` BIGINT UNSIGNED NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `UserId` VARCHAR(64) NOT NULL,
  `Status` CHAR(2) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `MobileNumber` CHAR(11) NULL DEFAULT NULL,
  `Type` CHAR(2) NOT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `LastModifiedTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VerificationCode` VARCHAR(128) NULL DEFAULT NULL,
  `VerificationSendDate` DATETIME NULL DEFAULT NULL,
  `PartyId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ProfileId`),
  CONSTRAINT `fk_profile_party1`
    FOREIGN KEY (`PartyId`)
    REFERENCES `trepubdotnet`.`party` (`PartyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_profile_party1_idx` ON `trepubdotnet`.`profile` (`PartyId` ASC);


-- -----------------------------------------------------
-- Table `trepubdotnet`.`roleitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`roleitem` (
  `RoleItemId` BIGINT UNSIGNED NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `Name` VARCHAR(64) NULL DEFAULT NULL,
  `Status` CHAR(2) NULL DEFAULT NULL,
  `LastModifiedTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RoleItemId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `trepubdotnet`.`profilerole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`profilerole` (
  `RoleItemId` BIGINT UNSIGNED NOT NULL,
  `ProfileId` BIGINT UNSIGNED NOT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `Status` CHAR(2) NULL DEFAULT NULL,
  `LastModifiedTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RoleItemId`, `ProfileId`),
  CONSTRAINT `R67`
    FOREIGN KEY (`RoleItemId`)
    REFERENCES `trepubdotnet`.`roleitem` (`RoleItemId`),
  CONSTRAINT `R68`
    FOREIGN KEY (`ProfileId`)
    REFERENCES `trepubdotnet`.`profile` (`ProfileId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `R68` ON `trepubdotnet`.`profilerole` (`ProfileId` ASC);


-- -----------------------------------------------------
-- Table `trepubdotnet`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`resource` (
  `ResourceId` BIGINT UNSIGNED NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `Name` VARCHAR(64) NULL DEFAULT NULL,
  `ResourceContent` VARCHAR(255) NULL DEFAULT NULL,
  `Status` CHAR(2) NULL DEFAULT NULL,
  `Type` CHAR(2) NULL DEFAULT NULL,
  `LastModifiedTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ResourceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `trepubdotnet`.`roleitemresource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trepubdotnet`.`roleitemresource` (
  `RoleItemId` BIGINT UNSIGNED NOT NULL,
  `ResourceId` BIGINT UNSIGNED NOT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `Status` CHAR(2) NULL DEFAULT NULL,
  `LastModifiedTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RoleItemId`, `ResourceId`),
  CONSTRAINT `R69`
    FOREIGN KEY (`RoleItemId`)
    REFERENCES `trepubdotnet`.`roleitem` (`RoleItemId`),
  CONSTRAINT `R70`
    FOREIGN KEY (`ResourceId`)
    REFERENCES `trepubdotnet`.`resource` (`ResourceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `R70` ON `trepubdotnet`.`roleitemresource` (`ResourceId` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
